# Noise Diagnostics and Detectability
This notebook performs noise statistics and detectability analysis for each Asym_* folder using the generated ingress, mid, and egress spectra.

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
work_dir = os.getcwd()
def load_phase_data(folder):
    base = os.path.join(work_dir, folder)
    def load_one(phase):
        path = os.path.join(base, f"{phase}.txt")
        data = np.loadtxt(path)
        return data
    return (load_one("ingress"), load_one("mid"), load_one("egress"))
def noise_diagnostics(folder):
    ing, mid, egr = load_phase_data(folder)
    for phase, data in [("Ingress", ing), ("Mid", mid), ("Egress", egr)]:
        λ = data[:, 0]
        total_flux = data[:, -1]
        noise = data[:, 2]
        snr = np.divide(total_flux, noise, out=np.zeros_like(total_flux), where=noise > 0)
        print(f"\n{folder} - {phase}")
        print(f"  Mean flux: {np.mean(total_flux):.6e}")
        print(f"  Flux min/max: {np.min(total_flux):.6e} / {np.max(total_flux):.6e}")
        print(f"  Mean noise: {np.mean(noise):.6e}")
        print(f"  Noise min/max: {np.min(noise):.6e} / {np.max(noise):.6e}")
        print(f"  Mean SNR: {np.mean(snr):.2f}, min: {np.min(snr):.2f}, max: {np.max(snr):.2f}")
        print(f"  Mean σ/F: {np.mean(noise/total_flux):.4f} ({100 * np.mean(noise/total_flux):.2f}%)")
        region_data = []
        for r1, r2 in [(0.80, 1.00), (1.00, 1.16), (1.16, 1.30), (1.30, 1.50), (1.50, 1.70), (1.70, 1.95), (1.95, 2.20)]:
            mask = (λ >= r1) & (λ <= r2)
            region_data.append({
                'Region [μm]': f"{r1}-{r2}",
                '<Flux>': np.mean(total_flux[mask]),
                '<σ>': np.mean(noise[mask]),
                '<SNR>': np.mean(snr[mask])
            })
        display(pd.DataFrame(region_data))
def detectability_analysis(folder):
    ing, egr = load_phase_data(folder)[0], load_phase_data(folder)[2]
    λ = ing[:, 0]
    f_ing = ing[:, -1]
    f_egr = egr[:, -1]
    ni = ing[:, 2]
    ne = egr[:, 2]
    σ_comb = np.sqrt(ni**2 + ne**2)
    diff_raw = f_ing - f_egr
    snr_diff = np.divide(diff_raw, σ_comb, out=np.zeros_like(diff_raw), where=σ_comb > 0)
    print(f"\n{folder} - Detectability")
    print(f"  Mean diff: {np.mean(diff_raw):.6e}")
    print(f"  Std diff: {np.std(diff_raw):.6e}")
    print(f"  Max |diff|: {np.max(np.abs(diff_raw)):.6e}")
    print(f"  Mean SNR: {np.mean(snr_diff):.4f}")
    print(f"  Min SNR: {np.min(snr_diff):.4f}, max SNR: {np.max(snr_diff):.4f}")
    region_data = []
    for r1, r2 in [(0.80, 1.00), (1.00, 1.16), (1.16, 1.30), (1.30, 1.50), (1.50, 1.70), (1.70, 1.95), (1.95, 2.20)]:
        mask = (λ >= r1) & (λ <= r2)
        region_data.append({
            'Region [μm]': f"{r1}-{r2}",
            '<SNR>': np.mean(snr_diff[mask]),
            'Max SNR': np.max(snr_diff[mask])
        })
    display(pd.DataFrame(region_data))

In [3]:
asymmetry_levels = np.arange(0.1, 1.01, 0.1)
folders = [f"Asym_{a:.1f}" for a in asymmetry_levels]
for folder in folders:
    noise_diagnostics(folder)
    detectability_analysis(folder)

Asym_0.1 - Ingress
  Mean flux: 1.705596e-02
  Flux min/max: 1.972520e-03 / 2.002780e-02
  Mean noise: 4.140634e-04
  Noise min/max: 1.846540e-04 / 5.995350e-04
  Mean SNR: 41.05, min: 10.50, max: 51.35
  Mean σ/F: 0.0262 (2.62%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018783  0.000375  50.112187
1    1.0-1.16  0.018493  0.000388  47.609706
2    1.16-1.3  0.019251  0.000415  46.338978
3     1.3-1.5  0.013109  0.000355  35.217229
4     1.5-1.7  0.019660  0.000479  41.029800
5    1.7-1.95  0.012531  0.000404  28.998706
6    1.95-2.2  0.017158  0.000533  31.847399

Asym_0.1 - Mid
  Mean flux: 1.691403e-02
  Flux min/max: 1.960180e-03 / 1.988500e-02
  Mean noise: 4.140967e-04
  Noise min/max: 1.846650e-04 / 5.995810e-04
  Mean SNR: 40.70, min: 10.43, max: 50.84
  Mean σ/F: 0.0265 (2.65%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018602  0.000375  49.624889
1    1.0-1.16  0.018323  0.000388  47.169712
2    1.16-1.3  0.019085  0.000416  45.933853
3     1.3-1.5  0.013019  0.000355  34.974382
4     1.5-1.7  0.019507  0.000479  40.708134
5    1.7-1.95  0.012442  0.000404  28.792672
6    1.95-2.2  0.017037  0.000533  31.621184

Asym_0.1 - Egress
  Mean flux: 1.681449e-02
  Flux min/max: 1.952510e-03 / 1.978910e-02
  Mean noise: 4.141200e-04
  Noise min/max: 1.846730e-04 / 5.996130e-04
  Mean SNR: 40.46, min: 10.39, max: 50.47
  Mean σ/F: 0.0266 (2.66%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018471  0.000375  49.271956
1    1.0-1.16  0.018200  0.000388  46.850285
2    1.16-1.3  0.018964  0.000416  45.642181
3     1.3-1.5  0.012959  0.000355  34.814034
4     1.5-1.7  0.019401  0.000479  40.484603
5    1.7-1.95  0.012382  0.000404  28.656449
6    1.95-2.2  0.016959  0.000533  31.476544

Asym_0.1 - Detectability
  Mean diff: 2.414730e-04
  Std diff: 8.471645e-05
  Max |diff|: 3.544000e-04
  Mean SNR: 0.4133
  Min SNR: 0.0753, max SNR: 0.6600

  Region [μm]     <SNR>   Max SNR
0     0.8-1.0  0.588308  0.660029
1    1.0-1.16  0.531676  0.606295
2    1.16-1.3  0.487783  0.515907
3     1.3-1.5  0.282273  0.500821
4     1.5-1.7  0.381667  0.425847
5    1.7-1.95  0.239682  0.410518
6    1.95-2.2  0.259784  0.316939

Asym_0.2 - Ingress
  Mean flux: 1.717528e-02
  Flux min/max: 1.982370e-03 / 2.014560e-02
  Mean noise: 4.140353e-04
  Noise min/max: 1.846450e-04 / 5.994970e-04
  Mean SNR: 41.34, min: 10.55, max: 51.79
  Mean σ/F: 0.0261 (2.61%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018938  0.000375  50.528837
1    1.0-1.16  0.018638  0.000388  47.985364
2    1.16-1.3  0.019393  0.000415  46.683062
3     1.3-1.5  0.013184  0.000355  35.415568
4     1.5-1.7  0.019788  0.000479  41.298471
5    1.7-1.95  0.012605  0.000404  29.167412
6    1.95-2.2  0.017257  0.000533  32.030644

Asym_0.2 - Mid
  Mean flux: 1.691403e-02
  Flux min/max: 1.960180e-03 / 1.988500e-02
  Mean noise: 4.140967e-04
  Noise min/max: 1.846650e-04 / 5.995810e-04
  Mean SNR: 40.70, min: 10.43, max: 50.84
  Mean σ/F: 0.0265 (2.65%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018602  0.000375  49.624889
1    1.0-1.16  0.018323  0.000388  47.169712
2    1.16-1.3  0.019085  0.000416  45.933853
3     1.3-1.5  0.013019  0.000355  34.974382
4     1.5-1.7  0.019507  0.000479  40.708134
5    1.7-1.95  0.012442  0.000404  28.792672
6    1.95-2.2  0.017037  0.000533  31.621184

Asym_0.2 - Egress
  Mean flux: 1.671494e-02
  Flux min/max: 1.944840e-03 / 1.969320e-02
  Mean noise: 4.141434e-04
  Noise min/max: 1.846800e-04 / 5.996450e-04
  Mean SNR: 40.21, min: 10.35, max: 50.12
  Mean σ/F: 0.0267 (2.67%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018340  0.000375  48.919044
1    1.0-1.16  0.018077  0.000388  46.530925
2    1.16-1.3  0.018844  0.000416  45.350547
3     1.3-1.5  0.012899  0.000355  34.653693
4     1.5-1.7  0.019294  0.000480  40.261095
5    1.7-1.95  0.012322  0.000404  28.520243
6    1.95-2.2  0.016881  0.000533  31.331911

Asym_0.2 - Detectability
  Mean diff: 4.603368e-04
  Std diff: 1.639178e-04
  Max |diff|: 6.816000e-04
  Mean SNR: 0.7882
  Min SNR: 0.1413, max SNR: 1.2694

  Region [μm]     <SNR>   Max SNR
0     0.8-1.0  1.127120  1.269353
1    1.0-1.16  1.018251  1.166124
2    1.16-1.3  0.932802  0.989375
3     1.3-1.5  0.533376  0.960147
4     1.5-1.7  0.726199  0.815109
5    1.7-1.95  0.453202  0.784673
6    1.95-2.2  0.489454  0.601315

Asym_0.3 - Ingress
  Mean flux: 1.728834e-02
  Flux min/max: 1.991530e-03 / 2.025720e-02
  Mean noise: 4.140088e-04
  Noise min/max: 1.846360e-04 / 5.994600e-04
  Mean SNR: 41.61, min: 10.60, max: 52.20
  Mean σ/F: 0.0259 (2.59%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.019085  0.000375  50.925764
1    1.0-1.16  0.018776  0.000388  48.343288
2    1.16-1.3  0.019528  0.000415  47.010450
3     1.3-1.5  0.013253  0.000355  35.601721
4     1.5-1.7  0.019909  0.000479  41.552674
5    1.7-1.95  0.012674  0.000404  29.325801
6    1.95-2.2  0.017349  0.000532  32.201865

Asym_0.3 - Mid
  Mean flux: 1.691403e-02
  Flux min/max: 1.960180e-03 / 1.988500e-02
  Mean noise: 4.140967e-04
  Noise min/max: 1.846650e-04 / 5.995810e-04
  Mean SNR: 40.70, min: 10.43, max: 50.84
  Mean σ/F: 0.0265 (2.65%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018602  0.000375  49.624889
1    1.0-1.16  0.018323  0.000388  47.169712
2    1.16-1.3  0.019085  0.000416  45.933853
3     1.3-1.5  0.013019  0.000355  34.974382
4     1.5-1.7  0.019507  0.000479  40.708134
5    1.7-1.95  0.012442  0.000404  28.792672
6    1.95-2.2  0.017037  0.000533  31.621184

Asym_0.3 - Egress
  Mean flux: 1.661540e-02
  Flux min/max: 1.937170e-03 / 1.960180e-02
  Mean noise: 4.141667e-04
  Noise min/max: 1.846880e-04 / 5.996760e-04
  Mean SNR: 39.97, min: 10.31, max: 49.81
  Mean σ/F: 0.0269 (2.69%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018209  0.000375  48.566201
1    1.0-1.16  0.017954  0.000388  46.211604
2    1.16-1.3  0.018724  0.000416  45.058949
3     1.3-1.5  0.012839  0.000355  34.493376
4     1.5-1.7  0.019188  0.000480  40.037622
5    1.7-1.95  0.012263  0.000404  28.384050
6    1.95-2.2  0.016803  0.000533  31.187299

Asym_0.3 - Detectability
  Mean diff: 6.729421e-04
  Std diff: 2.416030e-04
  Max |diff|: 1.001100e-03
  Mean SNR: 1.1524
  Min SNR: 0.2046, max SNR: 1.8644

  Region [μm]     <SNR>   Max SNR
0     0.8-1.0  1.652075  1.864370
1    1.0-1.16  1.492379  1.713135
2    1.16-1.3  1.366098  1.451034
3     1.3-1.5  0.775928  1.407781
4     1.5-1.7  1.060580  1.194405
5    1.7-1.95  0.659489  1.149065
6    1.95-2.2  0.710683  0.876606

Asym_0.4 - Ingress
  Mean flux: 1.739880e-02
  Flux min/max: 2.000400e-03 / 2.036600e-02
  Mean noise: 4.139829e-04
  Noise min/max: 1.846270e-04 / 5.994250e-04
  Mean SNR: 41.88, min: 10.65, max: 52.61
  Mean σ/F: 0.0258 (2.58%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.019230  0.000375  51.314464
1    1.0-1.16  0.018911  0.000388  48.693877
2    1.16-1.3  0.019659  0.000415  47.330960
3     1.3-1.5  0.013321  0.000355  35.782849
4     1.5-1.7  0.020027  0.000479  41.800918
5    1.7-1.95  0.012741  0.000404  29.479922
6    1.95-2.2  0.017439  0.000532  32.368058

Asym_0.4 - Mid
  Mean flux: 1.691403e-02
  Flux min/max: 1.960180e-03 / 1.988500e-02
  Mean noise: 4.140967e-04
  Noise min/max: 1.846650e-04 / 5.995810e-04
  Mean SNR: 40.70, min: 10.43, max: 50.84
  Mean σ/F: 0.0265 (2.65%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018602  0.000375  49.624889
1    1.0-1.16  0.018323  0.000388  47.169712
2    1.16-1.3  0.019085  0.000416  45.933853
3     1.3-1.5  0.013019  0.000355  34.974382
4     1.5-1.7  0.019507  0.000479  40.708134
5    1.7-1.95  0.012442  0.000404  28.792672
6    1.95-2.2  0.017037  0.000533  31.621184

Asym_0.4 - Egress
  Mean flux: 1.651585e-02
  Flux min/max: 1.929500e-03 / 1.951320e-02
  Mean noise: 4.141901e-04
  Noise min/max: 1.846950e-04 / 5.997080e-04
  Mean SNR: 39.72, min: 10.27, max: 49.50
  Mean σ/F: 0.0270 (2.70%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018078  0.000375  48.213403
1    1.0-1.16  0.017831  0.000388  45.892319
2    1.16-1.3  0.018604  0.000416  44.767395
3     1.3-1.5  0.012779  0.000355  34.333077
4     1.5-1.7  0.019082  0.000480  39.814166
5    1.7-1.95  0.012203  0.000404  28.247863
6    1.95-2.2  0.016725  0.000533  31.042696

Asym_0.4 - Detectability
  Mean diff: 8.829460e-04
  Std diff: 3.186583e-04
  Max |diff|: 1.317500e-03
  Mean SNR: 1.5121
  Min SNR: 0.2669, max SNR: 2.4535

  Region [μm]     <SNR>   Max SNR
0     0.8-1.0  2.171233  2.453512
1    1.0-1.16  1.961342  2.254817
2    1.16-1.3  1.794546  1.908023
3     1.3-1.5  1.014949  1.850971
4     1.5-1.7  1.390769  1.569575
5    1.7-1.95  0.862774  1.509357
6    1.95-2.2  0.928380  1.148005

Asym_0.5 - Ingress
  Mean flux: 1.750793e-02
  Flux min/max: 2.009130e-03 / 2.047340e-02
  Mean noise: 4.139573e-04
  Noise min/max: 1.846190e-04 / 5.993900e-04
  Mean SNR: 42.15, min: 10.70, max: 53.02
  Mean σ/F: 0.0256 (2.56%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.019372  0.000374  51.698990
1    1.0-1.16  0.019044  0.000388  49.040768
2    1.16-1.3  0.019790  0.000415  47.648005
3     1.3-1.5  0.013387  0.000355  35.961459
4     1.5-1.7  0.020143  0.000479  42.046196
5    1.7-1.95  0.012807  0.000404  29.631887
6    1.95-2.2  0.017527  0.000532  32.531700

Asym_0.5 - Mid
  Mean flux: 1.691403e-02
  Flux min/max: 1.960180e-03 / 1.988500e-02
  Mean noise: 4.140967e-04
  Noise min/max: 1.846650e-04 / 5.995810e-04
  Mean SNR: 40.70, min: 10.43, max: 50.84
  Mean σ/F: 0.0265 (2.65%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018602  0.000375  49.624889
1    1.0-1.16  0.018323  0.000388  47.169712
2    1.16-1.3  0.019085  0.000416  45.933853
3     1.3-1.5  0.013019  0.000355  34.974382
4     1.5-1.7  0.019507  0.000479  40.708134
5    1.7-1.95  0.012442  0.000404  28.792672
6    1.95-2.2  0.017037  0.000533  31.621184

Asym_0.5 - Egress
  Mean flux: 1.641630e-02
  Flux min/max: 1.921830e-03 / 1.942460e-02
  Mean noise: 4.142134e-04
  Noise min/max: 1.847030e-04 / 5.997400e-04
  Mean SNR: 39.48, min: 10.23, max: 49.19
  Mean σ/F: 0.0272 (2.72%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.017947  0.000375  47.860651
1    1.0-1.16  0.017708  0.000388  45.573089
2    1.16-1.3  0.018484  0.000416  44.475874
3     1.3-1.5  0.012719  0.000355  34.172790
4     1.5-1.7  0.018975  0.000480  39.590732
5    1.7-1.95  0.012144  0.000404  28.111699
6    1.95-2.2  0.016647  0.000533  30.898102

Asym_0.5 - Detectability
  Mean diff: 1.091632e-03
  Std diff: 3.953932e-04
  Max |diff|: 1.632200e-03
  Mean SNR: 1.8696
  Min SNR: 0.3286, max SNR: 3.0396

  Region [μm]     <SNR>   Max SNR
0     0.8-1.0  2.687429  3.039573
1    1.0-1.16  2.427679  2.793771
2    1.16-1.3  2.220543  2.362466
3     1.3-1.5  1.252192  2.291689
4     1.5-1.7  1.718866  1.942755
5    1.7-1.95  1.064537  1.867525
6    1.95-2.2  1.144285  1.417517

Asym_0.6 - Ingress
  Mean flux: 1.761632e-02
  Flux min/max: 2.017770e-03 / 2.057990e-02
  Mean noise: 4.139318e-04
  Noise min/max: 1.846110e-04 / 5.993550e-04
  Mean SNR: 42.42, min: 10.74, max: 53.42
  Mean σ/F: 0.0255 (2.55%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.019514  0.000374  52.081143
1    1.0-1.16  0.019177  0.000388  49.385577
2    1.16-1.3  0.019920  0.000415  47.963129
3     1.3-1.5  0.013454  0.000355  36.138652
4     1.5-1.7  0.020259  0.000479  42.289792
5    1.7-1.95  0.012873  0.000404  29.782639
6    1.95-2.2  0.017614  0.000532  32.693873

Asym_0.6 - Mid
  Mean flux: 1.691403e-02
  Flux min/max: 1.960180e-03 / 1.988500e-02
  Mean noise: 4.140967e-04
  Noise min/max: 1.846650e-04 / 5.995810e-04
  Mean SNR: 40.70, min: 10.43, max: 50.84
  Mean σ/F: 0.0265 (2.65%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018602  0.000375  49.624889
1    1.0-1.16  0.018323  0.000388  47.169712
2    1.16-1.3  0.019085  0.000416  45.933853
3     1.3-1.5  0.013019  0.000355  34.974382
4     1.5-1.7  0.019507  0.000479  40.708134
5    1.7-1.95  0.012442  0.000404  28.792672
6    1.95-2.2  0.017037  0.000533  31.621184

Asym_0.6 - Egress
  Mean flux: 1.631676e-02
  Flux min/max: 1.914160e-03 / 1.933590e-02
  Mean noise: 4.142367e-04
  Noise min/max: 1.847100e-04 / 5.997710e-04
  Mean SNR: 39.24, min: 10.19, max: 48.88
  Mean σ/F: 0.0274 (2.74%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.017816  0.000375  47.507950
1    1.0-1.16  0.017584  0.000388  45.253876
2    1.16-1.3  0.018364  0.000416  44.184383
3     1.3-1.5  0.012659  0.000355  34.012512
4     1.5-1.7  0.018869  0.000480  39.367329
5    1.7-1.95  0.012084  0.000404  27.975544
6    1.95-2.2  0.016569  0.000533  30.753525

Asym_0.6 - Detectability
  Mean diff: 1.299567e-03
  Std diff: 4.719454e-04
  Max |diff|: 1.945900e-03
  Mean SNR: 2.2259
  Min SNR: 0.3900, max SNR: 3.6239

  Region [μm]     <SNR>   Max SNR
0     0.8-1.0  3.201931  3.623925
1    1.0-1.16  2.892535  3.331210
2    1.16-1.3  2.645171  2.815520
3     1.3-1.5  1.488442  2.731094
4     1.5-1.7  2.045765  2.314795
5    1.7-1.95  1.265441  2.224565
6    1.95-2.2  1.359146  1.685851

Asym_0.7 - Ingress
  Mean flux: 1.772424e-02
  Flux min/max: 2.026360e-03 / 2.068600e-02
  Mean noise: 4.139065e-04
  Noise min/max: 1.846020e-04 / 5.993200e-04
  Mean SNR: 42.68, min: 10.79, max: 53.83
  Mean σ/F: 0.0253 (2.53%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.019655  0.000374  52.461827
1    1.0-1.16  0.019310  0.000387  49.729115
2    1.16-1.3  0.020049  0.000415  48.277074
3     1.3-1.5  0.013520  0.000355  36.314983
4     1.5-1.7  0.020374  0.000479  42.532372
5    1.7-1.95  0.012938  0.000404  29.932635
6    1.95-2.2  0.017701  0.000532  32.855151

Asym_0.7 - Mid
  Mean flux: 1.691403e-02
  Flux min/max: 1.960180e-03 / 1.988500e-02
  Mean noise: 4.140967e-04
  Noise min/max: 1.846650e-04 / 5.995810e-04
  Mean SNR: 40.70, min: 10.43, max: 50.84
  Mean σ/F: 0.0265 (2.65%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018602  0.000375  49.624889
1    1.0-1.16  0.018323  0.000388  47.169712
2    1.16-1.3  0.019085  0.000416  45.933853
3     1.3-1.5  0.013019  0.000355  34.974382
4     1.5-1.7  0.019507  0.000479  40.708134
5    1.7-1.95  0.012442  0.000404  28.792672
6    1.95-2.2  0.017037  0.000533  31.621184

Asym_0.7 - Egress
  Mean flux: 1.621721e-02
  Flux min/max: 1.906490e-03 / 1.924730e-02
  Mean noise: 4.142601e-04
  Noise min/max: 1.847180e-04 / 5.998030e-04
  Mean SNR: 38.99, min: 10.15, max: 48.58
  Mean σ/F: 0.0275 (2.75%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.017685  0.000375  47.155304
1    1.0-1.16  0.017461  0.000388  44.934734
2    1.16-1.3  0.018244  0.000416  43.892938
3     1.3-1.5  0.012599  0.000355  33.852265
4     1.5-1.7  0.018762  0.000480  39.143952
5    1.7-1.95  0.012025  0.000404  27.839399
6    1.95-2.2  0.016490  0.000533  30.608960

Asym_0.7 - Detectability
  Mean diff: 1.507034e-03
  Std diff: 5.483836e-04
  Max |diff|: 2.259100e-03
  Mean SNR: 2.5813
  Min SNR: 0.4512, max SNR: 4.2070

  Region [μm]     <SNR>   Max SNR
0     0.8-1.0  3.715365  4.207039
1    1.0-1.16  3.356459  3.867730
2    1.16-1.3  3.068937  3.267757
3     1.3-1.5  1.724065  3.169677
4     1.5-1.7  2.371928  2.685982
5    1.7-1.95  1.465810  2.580897
6    1.95-2.2  1.573370  1.953475

Asym_0.8 - Ingress
  Mean flux: 1.783186e-02
  Flux min/max: 2.034920e-03 / 2.079180e-02
  Mean noise: 4.138813e-04
  Noise min/max: 1.845940e-04 / 5.992850e-04
  Mean SNR: 42.94, min: 10.84, max: 54.23
  Mean σ/F: 0.0252 (2.52%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.019796  0.000374  52.841570
1    1.0-1.16  0.019442  0.000387  50.071834
2    1.16-1.3  0.020177  0.000415  48.590254
3     1.3-1.5  0.013585  0.000355  36.490751
4     1.5-1.7  0.020489  0.000479  42.774296
5    1.7-1.95  0.013003  0.000404  30.082152
6    1.95-2.2  0.017788  0.000532  33.015834

Asym_0.8 - Mid
  Mean flux: 1.691403e-02
  Flux min/max: 1.960180e-03 / 1.988500e-02
  Mean noise: 4.140967e-04
  Noise min/max: 1.846650e-04 / 5.995810e-04
  Mean SNR: 40.70, min: 10.43, max: 50.84
  Mean σ/F: 0.0265 (2.65%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018602  0.000375  49.624889
1    1.0-1.16  0.018323  0.000388  47.169712
2    1.16-1.3  0.019085  0.000416  45.933853
3     1.3-1.5  0.013019  0.000355  34.974382
4     1.5-1.7  0.019507  0.000479  40.708134
5    1.7-1.95  0.012442  0.000404  28.792672
6    1.95-2.2  0.017037  0.000533  31.621184

Asym_0.8 - Egress
  Mean flux: 1.611766e-02
  Flux min/max: 1.898830e-03 / 1.915870e-02
  Mean noise: 4.142834e-04
  Noise min/max: 1.847250e-04 / 5.998350e-04
  Mean SNR: 38.75, min: 10.10, max: 48.27
  Mean σ/F: 0.0277 (2.77%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.017554  0.000375  46.802704
1    1.0-1.16  0.017338  0.000388  44.615625
2    1.16-1.3  0.018124  0.000416  43.601542
3     1.3-1.5  0.012539  0.000355  33.692015
4     1.5-1.7  0.018656  0.000480  38.920596
5    1.7-1.95  0.011965  0.000404  27.703266
6    1.95-2.2  0.016412  0.000533  30.464407

Asym_0.8 - Detectability
  Mean diff: 1.714196e-03
  Std diff: 6.247449e-04
  Max |diff|: 2.571900e-03
  Mean SNR: 2.9362
  Min SNR: 0.5122, max SNR: 4.7896

  Region [μm]     <SNR>   Max SNR
0     0.8-1.0  4.228102  4.789587
1    1.0-1.16  3.819778  4.403535
2    1.16-1.3  3.492136  3.719621
3     1.3-1.5  1.959293  3.607932
4     1.5-1.7  2.697620  3.056743
5    1.7-1.95  1.665831  2.936664
6    1.95-2.2  1.787169  2.220633

Asym_0.9 - Ingress
  Mean flux: 1.793927e-02
  Flux min/max: 2.043460e-03 / 2.089740e-02
  Mean noise: 4.138561e-04
  Noise min/max: 1.845860e-04 / 5.992510e-04
  Mean SNR: 43.21, min: 10.88, max: 54.64
  Mean σ/F: 0.0250 (2.50%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.019937  0.000374  53.220678
1    1.0-1.16  0.019573  0.000387  50.414006
2    1.16-1.3  0.020306  0.000415  48.902945
3     1.3-1.5  0.013651  0.000355  36.666156
4     1.5-1.7  0.020604  0.000479  43.015794
5    1.7-1.95  0.013069  0.000404  30.231341
6    1.95-2.2  0.017874  0.000532  33.176105

Asym_0.9 - Mid
  Mean flux: 1.691403e-02
  Flux min/max: 1.960180e-03 / 1.988500e-02
  Mean noise: 4.140967e-04
  Noise min/max: 1.846650e-04 / 5.995810e-04
  Mean SNR: 40.70, min: 10.43, max: 50.84
  Mean σ/F: 0.0265 (2.65%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018602  0.000375  49.624889
1    1.0-1.16  0.018323  0.000388  47.169712
2    1.16-1.3  0.019085  0.000416  45.933853
3     1.3-1.5  0.013019  0.000355  34.974382
4     1.5-1.7  0.019507  0.000479  40.708134
5    1.7-1.95  0.012442  0.000404  28.792672
6    1.95-2.2  0.017037  0.000533  31.621184

Asym_0.9 - Egress
  Mean flux: 1.601812e-02
  Flux min/max: 1.891160e-03 / 1.907000e-02
  Mean noise: 4.143067e-04
  Noise min/max: 1.847330e-04 / 5.998660e-04
  Mean SNR: 38.51, min: 10.06, max: 47.96
  Mean σ/F: 0.0278 (2.78%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.017422  0.000375  46.450153
1    1.0-1.16  0.017215  0.000388  44.296562
2    1.16-1.3  0.018004  0.000416  43.310167
3     1.3-1.5  0.012479  0.000355  33.531795
4     1.5-1.7  0.018550  0.000480  38.697268
5    1.7-1.95  0.011905  0.000404  27.567148
6    1.95-2.2  0.016334  0.000533  30.319870

Asym_0.9 - Detectability
  Mean diff: 1.921149e-03
  Std diff: 7.010553e-04
  Max |diff|: 2.884500e-03
  Mean SNR: 3.2908
  Min SNR: 0.5733, max SNR: 5.3717

  Region [μm]     <SNR>   Max SNR
0     0.8-1.0  4.740356  5.371731
1    1.0-1.16  4.282685  4.938987
2    1.16-1.3  3.914973  4.171003
3     1.3-1.5  2.194244  4.045696
4     1.5-1.7  3.022994  3.427221
5    1.7-1.95  1.865613  3.292153
6    1.95-2.2  2.000667  2.487434

Asym_1.0 - Ingress
  Mean flux: 5.132803e-03
  Flux min/max: 5.836530e-04 / 5.974810e-03
  Mean noise: 4.169103e-04
  Noise min/max: 1.858810e-04 / 6.035540e-04
  Mean SNR: 12.27, min: 3.09, max: 15.54
  Mean σ/F: 0.0882 (8.82%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.005709  0.000377  15.126868
1    1.0-1.16  0.005605  0.000390  14.328105
2    1.16-1.3  0.005813  0.000418  13.894962
3     1.3-1.5  0.003902  0.000357  10.402911
4     1.5-1.7  0.005894  0.000483  12.214015
5    1.7-1.95  0.003736  0.000407   8.579271
6    1.95-2.2  0.005107  0.000536   9.411769

Asym_1.0 - Mid
  Mean flux: 1.691403e-02
  Flux min/max: 1.960180e-03 / 1.988500e-02
  Mean noise: 4.140967e-04
  Noise min/max: 1.846650e-04 / 5.995810e-04
  Mean SNR: 40.70, min: 10.43, max: 50.84
  Mean σ/F: 0.0265 (2.65%)

  Region [μm]    <Flux>       <σ>      <SNR>
0     0.8-1.0  0.018602  0.000375  49.624889
1    1.0-1.16  0.018323  0.000388  47.169712
2    1.16-1.3  0.019085  0.000416  45.933853
3     1.3-1.5  0.013019  0.000355  34.974382
4     1.5-1.7  0.019507  0.000479  40.708134
5    1.7-1.95  0.012442  0.000404  28.792672
6    1.95-2.2  0.017037  0.000533  31.621184

Asym_1.0 - Egress
  Mean flux: 3.006287e-03
  Flux min/max: 4.183370e-04 / 4.030080e-03
  Mean noise: 4.174329e-04
  Noise min/max: 1.860550e-04 / 6.042910e-04
  Mean SNR: 7.15, min: 2.21, max: 8.82
  Mean σ/F: 0.1454 (14.54%)

  Region [μm]    <Flux>       <σ>     <SNR>
0     0.8-1.0  0.002925  0.000378  7.742302
1    1.0-1.16  0.002993  0.000391  7.655464
2    1.16-1.3  0.003263  0.000419  7.793632
3     1.3-1.5  0.002607  0.000358  6.991950
4     1.5-1.7  0.003620  0.000483  7.505071
5    1.7-1.95  0.002450  0.000407  5.677162
6    1.95-2.2  0.003403  0.000537  6.294910

Asym_1.0 - Detectability
  Mean diff: 2.126516e-03
  Std diff: 7.775178e-04
  Max |diff|: 3.196020e-03
  Mean SNR: 3.6152
  Min SNR: 0.6186, max SNR: 5.9074

  Region [μm]     <SNR>   Max SNR
0     0.8-1.0  5.209730  5.907409
1    1.0-1.16  4.707060  5.431657
2    1.16-1.3  4.303665  4.588622
3     1.3-1.5  2.405563  4.449180
4     1.5-1.7  3.321119  3.764834
5    1.7-1.95  2.046695  3.615357
6    1.95-2.2  2.198279  2.731562